package by.mess.util.exception

class ConnectionFailedException : RuntimeException()
